version: '3.7'

services:
  endpoint:
    build:
      context: endpoint/
    volumes:
      - ./endpoint/:/src/
      - /src/node_modules
    env_file:
      - .env
    ports:
      - 8081:8081
    networks:
      - acs-network
  application:
    build:
      context: application/
    volumes:
      - ./application/:/src/
      - /src/node_modules
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - acs-network
  nginx:
    build:
      context: nginx/
    ports:
      - 80:80
    networks:
      - acs-network
    depends_on:
      - endpoint
      - application
      
networks:
  acs-network:
    driver: bridge